jQuery(function($){
 const api=(action,data={})=>$.post(SBAdmin.ajax,{action,nonce:SBAdmin.nonce,...data});
 $('.sb-tabs button').on('click',function(){const t=$(this).data('tab');$('.sb-tabs button').removeClass('active');$(this).addClass('active');$('[data-pane]').removeClass('active');$('[data-pane="'+t+'"]').addClass('active')});
 $('#sb-settings-form').on('submit',function(e){e.preventDefault();$('#sb-save-result').text('در حال ذخیره…');api('sb_save_settings',{data:$(this).serialize()}).done(r=>$('#sb-save-result').text(r.success?'ذخیره شد ✓':'خطا'))});
 $('.sb-media').on('click',function(){const target=$('#'+$(this).data('target'));const f=wp.media({title:'انتخاب تصویر',multiple:false});f.on('select',()=>target.val(f.state().get('selection').first().id));f.open()});
 $('#sb-test-bale').on('click',()=>api('sb_test_bale').done(r=>$('#sb-test-result').text(r.success?' ✓ '+r.data:' ✕ '+r.data)));
 $('#sb-set-bale-webhook').on('click',()=>api('sb_set_bale_webhook').done(r=>$('#sb-test-result').text(r.success?' ✓ '+r.data:' ✕ '+r.data)));
 const add=(box,html)=>{$(box).append(html.replaceAll('__i__',Date.now()))};
 $('#sb-add-social').on('click',()=>add('#sb-social-list','<div class="sb-repeat"><span class="sb-handle">⋮⋮</span><input name="socials[__i__][name]" placeholder="نام"><input name="socials[__i__][url]" placeholder="https://"><input name="socials[__i__][image]" placeholder="آدرس تصویر"><label><input type="checkbox" name="socials[__i__][enabled]" value="1" checked> فعال</label><button type="button" class="button-link-delete sb-remove">حذف</button></div>'));
 $('#sb-add-faq').on('click',()=>add('#sb-faq-list','<div class="sb-repeat"><span class="sb-handle">⋮⋮</span><input name="faqs[__i__][q_fa]" placeholder="سوال فارسی"><textarea name="faqs[__i__][a_fa]" placeholder="پاسخ فارسی"></textarea><input name="faqs[__i__][q_en]" placeholder="English question"><textarea name="faqs[__i__][a_en]" placeholder="English answer"></textarea><label><input type="checkbox" name="faqs[__i__][enabled]" value="1" checked> فعال</label><button type="button" class="button-link-delete sb-remove">حذف</button></div>'));
 $('#sb-add-agent').on('click',()=>add('#sb-agent-list','<div class="sb-repeat"><span class="sb-handle">⋮⋮</span><input name="agents[__i__][name]" placeholder="نام اپراتور"><input name="agents[__i__][role]" placeholder="سمت"><input name="agents[__i__][image]" placeholder="آدرس عکس"><input name="agents[__i__][url]" placeholder="لینک بله/شبکه اجتماعی"><label><input type="checkbox" name="agents[__i__][enabled]" value="1" checked> فعال</label><button type="button" class="button-link-delete sb-remove">حذف</button></div>'));
 $(document).on('click','.sb-remove',function(){$(this).closest('.sb-repeat').remove()});$('.sb-repeat').parent().sortable({handle:'.sb-handle'});
 let cid=0; function loadList(){if(!$('#sb-conv-list').length)return;api('sb_admin_list').done(r=>{if(!r.success)return;$('#sb-conv-list').html(r.data.map(x=>`<button data-id="${x.id}"><b>#${x.id} ${x.name||'کاربر'}</b><small>${x.updated_at}</small></button>`).join(''))})} function loadMsgs(){if(!cid)return;api('sb_admin_messages',{id:cid}).done(r=>{if(r.success)$('#sb-admin-messages').html(r.data.map(x=>`<div class="m ${x.sender_type}"><span>${$('<div>').text(x.message).html()}</span><small>${x.created_at}</small></div>`).join('')).scrollTop(999999)})}
 $(document).on('click','#sb-conv-list button',function(){cid=$(this).data('id');$('#sb-conv-head').text('گفتگو #'+cid);loadMsgs()});$('#sb-admin-reply').on('submit',function(e){e.preventDefault();const ta=$(this).find('textarea');api('sb_admin_send',{id:cid,message:ta.val()}).done(r=>{if(r.success){ta.val('');loadMsgs()}})});loadList();setInterval(()=>{loadList();loadMsgs()},5000);
});
