<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class SB_Plugin {
    private static $instance;
    public static function instance(){ return self::$instance ?: ( self::$instance = new self() ); }
    public function boot(){
        add_action('admin_menu',[$this,'admin_menu']); add_action('admin_enqueue_scripts',[$this,'admin_assets']);
        add_action('wp_enqueue_scripts',[$this,'public_assets']); add_action('wp_footer',[$this,'render_widget']);
        foreach(['sb_save_settings'=>'ajax_save_settings','sb_test_bale'=>'ajax_test_bale','sb_set_bale_webhook'=>'ajax_set_bale_webhook','sb_admin_send'=>'ajax_admin_send','sb_admin_list'=>'ajax_admin_list','sb_admin_messages'=>'ajax_admin_messages'] as $a=>$m) add_action('wp_ajax_'.$a,[$this,$m]);
        foreach(['sb_start_chat'=>'ajax_start_chat','sb_send_message'=>'ajax_send_message','sb_poll_messages'=>'ajax_poll_messages'] as $a=>$m){ add_action('wp_ajax_'.$a,[$this,$m]); add_action('wp_ajax_nopriv_'.$a,[$this,$m]); }
        add_action('rest_api_init',[$this,'rest_routes']); add_action('sb_cleanup_event',[$this,'cleanup_old_data']);
        if(!wp_next_scheduled('sb_cleanup_event')) wp_schedule_event(time()+HOUR_IN_SECONDS,'daily','sb_cleanup_event');
    }
    public function settings(){ return wp_parse_args(get_option('sb_settings',[]),SB_Install::defaults()); }
    private function clean_nested($v){ $o=[]; foreach((array)$v as $k=>$x){ $k=is_int($k)?$k:sanitize_key($k); $o[$k]=is_array($x)?$this->clean_nested($x):(is_numeric($x)?$x:sanitize_text_field(wp_unslash($x))); } return $o; }
    private function sanitize_settings($in){
        $d=SB_Install::defaults(); $o=$this->settings();
        foreach(['enabled','faq_enabled','chat_enabled','social_enabled','bale_enabled','notify_bale'] as $k) $o[$k]=empty($in[$k])?0:1;
        foreach(['button_text_fa','button_text_en','button_position','button_animation','panel_mode','theme','welcome_fa','welcome_en','offline_fa','offline_en','online_mode','manual_status','bale_chat_id'] as $k) if(isset($in[$k])) $o[$k]=sanitize_text_field($in[$k]);
        foreach(['bale_support_url','bale_api_base'] as $k) if(isset($in[$k])) $o[$k]=esc_url_raw($in[$k]);
        if(isset($in['bale_bot_token'])) $o['bale_bot_token']=sanitize_text_field($in['bale_bot_token']);
        foreach(['button_color','button_text_color','primary_color','panel_bg','panel_text'] as $k) if(isset($in[$k])) $o[$k]=sanitize_hex_color($in[$k])?:$d[$k];
        $o['button_image_id']=absint($in['button_image_id']??0); $o['button_size']=max(40,min(96,absint($in['button_size']??58))); $o['button_radius']=max(0,min(50,absint($in['button_radius']??50))); $o['privacy_retention_days']=max(1,min(3650,absint($in['privacy_retention_days']??90)));
        foreach(['socials','faqs','agents','working_hours'] as $k) if(isset($in[$k])) $o[$k]=$this->clean_nested($in[$k]); return $o;
    }
    public function admin_menu(){ add_menu_page('Support Button','Support','manage_options','support-button',[$this,'page_dashboard'],'dashicons-format-chat',58); add_submenu_page('support-button','Conversations','گفتگوها','manage_options','support-button-conversations',[$this,'page_conversations']); add_submenu_page('support-button','Settings','تنظیمات','manage_options','support-button-settings',[$this,'page_settings']); }
    public function admin_assets($hook){ if(strpos($hook,'support-button')===false)return; wp_enqueue_media(); wp_enqueue_style('sb-admin',SB_URL.'admin/css/admin.css',[],SB_VERSION); wp_enqueue_script('sb-admin',SB_URL.'admin/js/admin.js',['jquery','jquery-ui-sortable'],SB_VERSION,true); wp_localize_script('sb-admin','SBAdmin',['ajax'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('sb_admin')]); }
    public function public_assets(){ if(empty($this->settings()['enabled']))return; wp_enqueue_style('sb-public',SB_URL.'public/css/public.css',[],SB_VERSION); wp_enqueue_script('sb-public',SB_URL.'public/js/public.js',[],SB_VERSION,true); wp_localize_script('sb-public','SBFront',['ajax'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('sb_front'),'locale'=>determine_locale()]); }
    private function is_online($s){ if(($s['online_mode']??'schedule')==='manual')return ($s['manual_status']??'online')==='online'; $map=['Sat'=>'sat','Sun'=>'sun','Mon'=>'mon','Tue'=>'tue','Wed'=>'wed','Thu'=>'thu','Fri'=>'fri']; $h=$s['working_hours'][$map[wp_date('D')]??'sat']??['enabled'=>0]; $n=wp_date('H:i'); return !empty($h['enabled'])&&$n>=($h['from']??'00:00')&&$n<=($h['to']??'23:59'); }
    public function render_widget(){ $s=$this->settings(); if(empty($s['enabled']))return; $fa=strpos(determine_locale(),'fa')===0; $txt=$fa?$s['button_text_fa']:$s['button_text_en']; $online=$this->is_online($s); $welcome=$fa?$s['welcome_fa']:$s['welcome_en']; $offline=$fa?$s['offline_fa']:$s['offline_en']; $img=$s['button_image_id']?wp_get_attachment_image_url($s['button_image_id'],'thumbnail'):''; ?>
<div id="sb-root" dir="<?php echo $fa?'rtl':'ltr'; ?>" data-online="<?php echo $online?'1':'0'; ?>"><button id="sb-launcher" class="sb-pos-<?php echo esc_attr($s['button_position']); ?> sb-anim-<?php echo esc_attr($s['button_animation']); ?>" style="--sb-btn:<?php echo esc_attr($s['button_color']); ?>;--sb-btn-text:<?php echo esc_attr($s['button_text_color']); ?>;--sb-size:<?php echo (int)$s['button_size']; ?>px;--sb-radius:<?php echo (int)$s['button_radius']; ?>%;"><?php if($img):?><img src="<?php echo esc_url($img); ?>" alt=""><?php else:?><span class="sb-bubble">💬</span><?php endif;?><span><?php echo esc_html($txt); ?></span></button>
<section id="sb-panel" class="sb-theme-<?php echo esc_attr($s['theme']); ?> sb-mode-<?php echo esc_attr($s['panel_mode']); ?>" style="--sb-primary:<?php echo esc_attr($s['primary_color']); ?>;--sb-bg:<?php echo esc_attr($s['panel_bg']); ?>;--sb-text:<?php echo esc_attr($s['panel_text']); ?>;" hidden><header><div><strong><?php echo esc_html($txt); ?></strong><small class="sb-status <?php echo $online?'online':'offline'; ?>"><?php echo esc_html($online?($fa?'آنلاین':'Online'):($fa?'آفلاین':'Offline')); ?></small></div><button id="sb-close" aria-label="Close">×</button></header><div class="sb-body"><p class="sb-welcome"><?php echo esc_html($online?$welcome:$offline); ?></p>
<?php if(!empty($s['chat_enabled'])):?><div class="sb-chat"><div id="sb-messages"></div><form id="sb-chat-form"><input id="sb-message" maxlength="2000" placeholder="<?php echo esc_attr($fa?'پیام خود را بنویسید…':'Type your message…'); ?>" required><button>➤</button></form></div><?php endif;?>
<?php if(!empty($s['faq_enabled'])):?><div class="sb-section"><h4><?php echo $fa?'سوالات متداول':'FAQ'; ?></h4><div class="sb-faqs"><?php foreach((array)$s['faqs'] as $x){ if(empty($x['enabled']))continue; $q=$fa?($x['q_fa']??''):($x['q_en']??''); $a=$fa?($x['a_fa']??''):($x['a_en']??''); if($q)echo '<details><summary>'.esc_html($q).'</summary><p>'.esc_html($a).'</p></details>'; }?></div></div><?php endif;?>
<?php if(!$online):?><div class="sb-section"><h4><?php echo $fa?'پشتیبان‌ها':'Support agents'; ?></h4><?php foreach((array)$s['agents'] as $a){ if(empty($a['enabled']))continue; echo '<div class="sb-agent">'; if(!empty($a['image']))echo '<img src="'.esc_url($a['image']).'" alt="">'; echo '<div><b>'.esc_html($a['name']??'').'</b><small>'.esc_html($a['role']??'').'</small></div>'; if(!empty($a['url']))echo '<a target="_blank" rel="noopener noreferrer" href="'.esc_url($a['url']).'">↗</a>'; echo '</div>'; }?></div><?php endif;?>
<?php if(!empty($s['social_enabled'])):?><div class="sb-section"><h4><?php echo $fa?'راه‌های ارتباطی':'Contact'; ?></h4><div class="sb-socials"><?php foreach((array)$s['socials'] as $x){ if(empty($x['enabled'])||empty($x['url']))continue; echo '<a target="_blank" rel="noopener noreferrer" href="'.esc_url($x['url']).'">'; if(!empty($x['image']))echo '<img src="'.esc_url($x['image']).'" alt="">'; echo '<span>'.esc_html($x['name']??'').'</span></a>'; }?></div></div><?php endif;?>
</div></section></div><?php }
    public function page_dashboard(){ global $wpdb; $c=$wpdb->prefix.'sb_conversations'; $m=$wpdb->prefix.'sb_messages'; $open=(int)$wpdb->get_var("SELECT COUNT(*) FROM $c WHERE status='open'"); $total=(int)$wpdb->get_var("SELECT COUNT(*) FROM $c"); $msgs=(int)$wpdb->get_var("SELECT COUNT(*) FROM $m"); echo '<div class="wrap sb-admin"><h1>Support Button</h1><div class="sb-cards"><div><b>'.$open.'</b><span>گفتگوهای باز</span></div><div><b>'.$total.'</b><span>کل گفتگوها</span></div><div><b>'.$msgs.'</b><span>پیام‌ها</span></div></div><p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=support-button-conversations')).'">مشاهده گفتگوها</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=support-button-settings')).'">تنظیمات</a></p></div>'; }
    public function page_conversations(){ echo '<div class="wrap sb-admin"><h1>گفتگوها</h1><div class="sb-inbox"><aside><input id="sb-search" placeholder="جستجو…"><div id="sb-conv-list"></div></aside><main><div id="sb-conv-head">یک گفتگو را انتخاب کنید</div><div id="sb-admin-messages"></div><form id="sb-admin-reply"><textarea placeholder="پاسخ…" required></textarea><button class="button button-primary">ارسال</button></form></main></div></div>'; }
    private function field($label,$html){ echo '<div class="sb-field"><label>'.esc_html($label).'</label>'.$html.'</div>'; }
    private function text($k,$l,$s,$type='text'){ $this->field($l,'<input type="'.$type.'" name="'.esc_attr($k).'" value="'.esc_attr($s[$k]??'').'">'); }
    private function check($k,$l,$s){ $this->field($l,'<label class="sb-switch"><input type="checkbox" name="'.esc_attr($k).'" value="1" '.checked(!empty($s[$k]),true,false).'><span></span></label>'); }
    private function select($k,$l,$o,$s){ $h='<select name="'.esc_attr($k).'">'; foreach($o as $v=>$t)$h.='<option value="'.esc_attr($v).'" '.selected($s[$k]??'',$v,false).'>'.esc_html($t).'</option>'; $this->field($l,$h.'</select>'); }
    private function social_row($i,$x){ echo '<div class="sb-repeat"><span class="sb-handle">⋮⋮</span><input name="socials['.$i.'][name]" placeholder="نام" value="'.esc_attr($x['name']??'').'"><input name="socials['.$i.'][url]" placeholder="https://" value="'.esc_attr($x['url']??'').'"><input name="socials['.$i.'][image]" placeholder="آدرس تصویر" value="'.esc_attr($x['image']??'').'"><label><input type="checkbox" name="socials['.$i.'][enabled]" value="1" '.checked(!empty($x['enabled']),true,false).'> فعال</label><button type="button" class="button-link-delete sb-remove">حذف</button></div>'; }
    private function faq_row($i,$x){ echo '<div class="sb-repeat sb-faq-row"><span class="sb-handle">⋮⋮</span><input name="faqs['.$i.'][q_fa]" placeholder="سوال فارسی" value="'.esc_attr($x['q_fa']??'').'"><textarea name="faqs['.$i.'][a_fa]" placeholder="پاسخ فارسی">'.esc_textarea($x['a_fa']??'').'</textarea><input name="faqs['.$i.'][q_en]" placeholder="English question" value="'.esc_attr($x['q_en']??'').'"><textarea name="faqs['.$i.'][a_en]" placeholder="English answer">'.esc_textarea($x['a_en']??'').'</textarea><label><input type="checkbox" name="faqs['.$i.'][enabled]" value="1" '.checked(!empty($x['enabled']),true,false).'> فعال</label><button type="button" class="button-link-delete sb-remove">حذف</button></div>'; }
    private function agent_row($i,$x){ echo '<div class="sb-repeat"><span class="sb-handle">⋮⋮</span><input name="agents['.$i.'][name]" placeholder="نام اپراتور" value="'.esc_attr($x['name']??'').'"><input name="agents['.$i.'][role]" placeholder="سمت" value="'.esc_attr($x['role']??'').'"><input name="agents['.$i.'][image]" placeholder="آدرس عکس" value="'.esc_attr($x['image']??'').'"><input name="agents['.$i.'][url]" placeholder="لینک ارتباط" value="'.esc_attr($x['url']??'').'"><label><input type="checkbox" name="agents['.$i.'][enabled]" value="1" '.checked(!empty($x['enabled']),true,false).'> فعال</label><button type="button" class="button-link-delete sb-remove">حذف</button></div>'; }
    public function page_settings(){ $s=$this->settings(); $days=['sat'=>'شنبه','sun'=>'یکشنبه','mon'=>'دوشنبه','tue'=>'سه‌شنبه','wed'=>'چهارشنبه','thu'=>'پنجشنبه','fri'=>'جمعه']; ?>
<div class="wrap sb-admin"><h1>تنظیمات Support Button</h1><form id="sb-settings-form"><nav class="sb-tabs"><?php foreach(['general'=>'عمومی','appearance'=>'ظاهر','content'=>'FAQ و اجتماعی','agents'=>'اپراتورها','bale'=>'بله','hours'=>'ساعات کاری','privacy'=>'حریم خصوصی','about'=>'درباره افزونه'] as $k=>$v)echo '<button type="button" data-tab="'.$k.'"'.($k==='general'?' class="active"':'').'>'.$v.'</button>';?></nav>
<section data-pane="general" class="active"><?php $this->check('enabled','فعال بودن افزونه',$s);$this->text('button_text_fa','متن دکمه فارسی',$s);$this->text('button_text_en','Button text English',$s);$this->text('welcome_fa','پیام خوش‌آمد فارسی',$s);$this->text('welcome_en','Welcome English',$s);$this->text('offline_fa','پیام آفلاین فارسی',$s);$this->text('offline_en','Offline English',$s);$this->check('chat_enabled','چت داخل سایت',$s);$this->check('faq_enabled','سوالات متداول',$s);$this->check('social_enabled','شبکه‌های اجتماعی',$s);?></section>
<section data-pane="appearance"><div class="sb-field"><label>تصویر دکمه</label><input type="hidden" name="button_image_id" id="button_image_id" value="<?php echo (int)$s['button_image_id'];?>"><button type="button" class="button sb-media" data-target="button_image_id">انتخاب تصویر</button></div><?php $this->select('button_position','موقعیت',['left'=>'پایین چپ','right'=>'پایین راست'],$s);$this->text('button_size','اندازه دکمه',$s,'number');$this->text('button_radius','گردی',$s,'number'); foreach(['button_color'=>'رنگ دکمه','button_text_color'=>'رنگ متن','primary_color'=>'رنگ اصلی','panel_bg'=>'پس‌زمینه پنل','panel_text'=>'رنگ متن پنل'] as $k=>$l)$this->text($k,$l,$s,'color'); $this->select('button_animation','انیمیشن',['none'=>'بدون','pulse'=>'Pulse','float'=>'Float'],$s);$this->select('panel_mode','نوع بازشدن',['popup'=>'پنجره شناور','drawer'=>'پنل کناری','modal'=>'مرکزی'],$s);$this->select('theme','تم',['minimal-light'=>'مینیمال روشن','minimal-dark'=>'مینیمال تیره','glass'=>'شیشه‌ای','brand'=>'برند'],$s);?><div class="sb-preview"><b>پیش‌نمایش</b><div class="sb-preview-card">سلام 👋<br><button type="button">شروع گفتگو</button></div></div></section>
<section data-pane="content"><h2>شبکه‌های اجتماعی</h2><div id="sb-social-list"><?php foreach((array)$s['socials'] as $i=>$x)$this->social_row($i,$x);?></div><button type="button" class="button" id="sb-add-social">+ افزودن شبکه</button><h2>سوالات متداول</h2><div id="sb-faq-list"><?php foreach((array)$s['faqs'] as $i=>$x)$this->faq_row($i,$x);?></div><button type="button" class="button" id="sb-add-faq">+ افزودن سوال</button></section>
<section data-pane="agents"><div id="sb-agent-list"><?php foreach((array)$s['agents'] as $i=>$x)$this->agent_row($i,$x);?></div><button type="button" class="button" id="sb-add-agent">+ افزودن اپراتور</button></section>
<section data-pane="bale"><?php $this->check('bale_enabled','فعال‌سازی اتصال بله',$s);$this->text('bale_bot_token','Bot Token',$s,'password');$this->text('bale_chat_id','Chat ID / شناسه مقصد',$s);$this->text('bale_support_url','لینک مستقیم پشتیبانی بله',$s);$this->text('bale_api_base','Bale API Base',$s);$this->check('notify_bale','ارسال اعلان پیام جدید به بله',$s);?><div class="sb-field"><label>Webhook URL</label><code><?php echo esc_html(rest_url('support-button/v1/bale-webhook/'.$s['bale_webhook_secret']));?></code></div><button type="button" class="button" id="sb-test-bale">تست اتصال</button> <button type="button" class="button" id="sb-set-bale-webhook">ثبت Webhook بله</button><span id="sb-test-result"></span></section>
<section data-pane="hours"><?php $this->select('online_mode','وضعیت آنلاین',['schedule'=>'طبق ساعات کاری','manual'=>'دستی'],$s);$this->select('manual_status','وضعیت دستی',['online'=>'آنلاین','offline'=>'آفلاین'],$s);?><table class="widefat"><thead><tr><th>روز</th><th>فعال</th><th>از</th><th>تا</th></tr></thead><tbody><?php foreach($days as $k=>$label){$h=$s['working_hours'][$k]??[];echo '<tr><td>'.$label.'</td><td><input type="checkbox" name="working_hours['.$k.'][enabled]" value="1" '.checked(!empty($h['enabled']),true,false).'></td><td><input type="time" name="working_hours['.$k.'][from]" value="'.esc_attr($h['from']??'09:00').'"></td><td><input type="time" name="working_hours['.$k.'][to]" value="'.esc_attr($h['to']??'18:00').'"></td></tr>'; }?></tbody></table></section>
<section data-pane="privacy"><?php $this->text('privacy_retention_days','مدت نگهداری گفتگوها (روز)',$s,'number');?><p>پیام‌ها پس از مدت تعیین‌شده به‌صورت روزانه پاک می‌شوند.</p></section>
<section data-pane="about"><div class="sb-about"><h2>Support Button</h2><p>افزونه Support Button یک راهکار سبک و قابل شخصی‌سازی برای پشتیبانی کاربران در وردپرس است؛ شامل گفتگوی داخل سایت، سوالات متداول، شبکه‌های اجتماعی، اپراتورها، ساعات کاری، تم‌های مختلف و اتصال اختیاری به بله.</p><p><strong>توسعه‌دهنده:</strong> سهند رضوان — Sahand Rezvan</p><p><strong>ارتباط:</strong> <a href="https://t.me/sahandse" target="_blank" rel="noopener noreferrer">t.me/sahandse</a></p><p><strong>نسخه:</strong> <?php echo esc_html(SB_VERSION);?></p><p class="description">Open-source WordPress support plugin for public use and distribution under GPLv2 or later.</p></div></section><p><button class="button button-primary button-large" type="submit">ذخیره تغییرات</button> <span id="sb-save-result"></span></p></form></div><?php }
    public function ajax_save_settings(){ check_ajax_referer('sb_admin','nonce'); if(!current_user_can('manage_options'))wp_send_json_error(); parse_str(wp_unslash($_POST['data']??''),$d); update_option('sb_settings',$this->sanitize_settings($d)); wp_send_json_success(); }
    public function ajax_start_chat(){ check_ajax_referer('sb_front','nonce'); global $wpdb; $pub=sanitize_text_field($_POST['public_id']??'')?:wp_generate_uuid4(); $t=$wpdb->prefix.'sb_conversations'; $id=$wpdb->get_var($wpdb->prepare("SELECT id FROM $t WHERE public_id=%s",$pub)); if(!$id){$n=current_time('mysql');$wpdb->insert($t,['public_id'=>$pub,'locale'=>sanitize_text_field($_POST['locale']??''),'page_url'=>esc_url_raw($_POST['page_url']??''),'created_at'=>$n,'updated_at'=>$n]);$id=$wpdb->insert_id;} wp_send_json_success(['public_id'=>$pub,'id'=>(int)$id]); }
    public function ajax_send_message(){ check_ajax_referer('sb_front','nonce'); global $wpdb; $pub=sanitize_text_field($_POST['public_id']??''); $msg=sanitize_textarea_field(wp_unslash($_POST['message']??'')); if(!$pub||!$msg)wp_send_json_error(); $ct=$wpdb->prefix.'sb_conversations';$mt=$wpdb->prefix.'sb_messages';$id=$wpdb->get_var($wpdb->prepare("SELECT id FROM $ct WHERE public_id=%s",$pub)); if(!$id)wp_send_json_error();$n=current_time('mysql');$wpdb->insert($mt,['conversation_id'=>$id,'sender_type'=>'visitor','message'=>$msg,'source'=>'website','created_at'=>$n]);$local=$wpdb->insert_id;$wpdb->update($ct,['updated_at'=>$n],['id'=>$id]);if(!empty($this->settings()['notify_bale'])){$r=$this->bale_send("🔔 پیام جدید سایت
Conversation #$id

$msg

برای پاسخ روی همین پیام Reply کنید.");if(!is_wp_error($r)){ $bid=$r['result']['message_id']??($r['message_id']??''); if($bid)$wpdb->update($mt,['external_message_id'=>(string)$bid],['id'=>$local]);}} wp_send_json_success(['id'=>$local]); }
    public function ajax_poll_messages(){ check_ajax_referer('sb_front','nonce');global $wpdb;$pub=sanitize_text_field($_POST['public_id']??'');$after=absint($_POST['after']??0);$ct=$wpdb->prefix.'sb_conversations';$mt=$wpdb->prefix.'sb_messages';$id=$wpdb->get_var($wpdb->prepare("SELECT id FROM $ct WHERE public_id=%s",$pub));if(!$id)wp_send_json_success([]);wp_send_json_success($wpdb->get_results($wpdb->prepare("SELECT id,sender_type,message,created_at FROM $mt WHERE conversation_id=%d AND id>%d ORDER BY id ASC LIMIT 100",$id,$after),ARRAY_A)); }
    public function ajax_admin_list(){ check_ajax_referer('sb_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();global $wpdb;$t=$wpdb->prefix.'sb_conversations';wp_send_json_success($wpdb->get_results("SELECT * FROM $t ORDER BY updated_at DESC LIMIT 200",ARRAY_A)); }
    public function ajax_admin_messages(){ check_ajax_referer('sb_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();global $wpdb;$id=absint($_POST['id']??0);$t=$wpdb->prefix.'sb_messages';wp_send_json_success($wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE conversation_id=%d ORDER BY id ASC LIMIT 500",$id),ARRAY_A)); }
    public function ajax_admin_send(){ check_ajax_referer('sb_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();global $wpdb;$id=absint($_POST['id']??0);$msg=sanitize_textarea_field(wp_unslash($_POST['message']??''));if(!$id||!$msg)wp_send_json_error();$n=current_time('mysql');$wpdb->insert($wpdb->prefix.'sb_messages',['conversation_id'=>$id,'sender_type'=>'agent','sender_id'=>get_current_user_id(),'message'=>$msg,'source'=>'admin','created_at'=>$n]);$wpdb->update($wpdb->prefix.'sb_conversations',['updated_at'=>$n],['id'=>$id]);wp_send_json_success(); }
    private function bale_send($text){$s=$this->settings();if(empty($s['bale_enabled'])||empty($s['bale_bot_token'])||empty($s['bale_chat_id']))return new WP_Error('bale','Bale is not configured.');$url=rtrim($s['bale_api_base']?:'https://tapi.bale.ai','/').'/bot'.$s['bale_bot_token'].'/sendMessage';$r=wp_remote_post($url,['timeout'=>15,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode(['chat_id'=>$s['bale_chat_id'],'text'=>$text])]);if(is_wp_error($r))return $r;$c=wp_remote_retrieve_response_code($r);return ($c<200||$c>=300)?new WP_Error('bale_http','Bale HTTP '.$c):json_decode(wp_remote_retrieve_body($r),true);}
    public function ajax_test_bale(){ check_ajax_referer('sb_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();$r=$this->bale_send('✅ Support Button test message');is_wp_error($r)?wp_send_json_error($r->get_error_message()):wp_send_json_success('ارسال شد'); }
    public function ajax_set_bale_webhook(){ check_ajax_referer('sb_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();$s=$this->settings();if(empty($s['bale_enabled'])||empty($s['bale_bot_token']))wp_send_json_error('ابتدا توکن بله را ذخیره کنید.');$url=rtrim($s['bale_api_base']?:'https://tapi.bale.ai','/').'/bot'.$s['bale_bot_token'].'/setWebhook';$r=wp_remote_post($url,['timeout'=>15,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode(['url'=>rest_url('support-button/v1/bale-webhook/'.$s['bale_webhook_secret'])])]);is_wp_error($r)?wp_send_json_error($r->get_error_message()):wp_send_json_success('Webhook ثبت شد'); }
    public function rest_routes(){ register_rest_route('support-button/v1','/bale-webhook/(?P<secret>[A-Za-z0-9_-]+)',['methods'=>'POST','callback'=>[$this,'bale_webhook'],'permission_callback'=>'__return_true']); }
    public function bale_webhook($r){$s=$this->settings();if(!hash_equals((string)$s['bale_webhook_secret'],(string)$r['secret']))return new WP_REST_Response(['ok'=>false],403);$d=$r->get_json_params();$m=$d['message']??[];$text=sanitize_textarea_field($m['text']??'');$reply=absint($m['reply_to_message']['message_id']??0);if(!$text||!$reply)return ['ok'=>true];global $wpdb;$cid=(int)$wpdb->get_var($wpdb->prepare("SELECT conversation_id FROM {$wpdb->prefix}sb_messages WHERE external_message_id=%s LIMIT 1",(string)$reply));if($cid){$n=current_time('mysql');$wpdb->insert($wpdb->prefix.'sb_messages',['conversation_id'=>$cid,'sender_type'=>'agent','message'=>$text,'source'=>'bale','external_message_id'=>(string)absint($m['message_id']??0),'created_at'=>$n]);$wpdb->update($wpdb->prefix.'sb_conversations',['updated_at'=>$n],['id'=>$cid]);}return ['ok'=>true];}
    public function cleanup_old_data(){global $wpdb;$cut=gmdate('Y-m-d H:i:s',time()-DAY_IN_SECONDS*(int)$this->settings()['privacy_retention_days']);$ct=$wpdb->prefix.'sb_conversations';$mt=$wpdb->prefix.'sb_messages';$ids=$wpdb->get_col($wpdb->prepare("SELECT id FROM $ct WHERE updated_at < %s",$cut));if($ids){$in=implode(',',array_map('absint',$ids));$wpdb->query("DELETE FROM $mt WHERE conversation_id IN ($in)");$wpdb->query("DELETE FROM $ct WHERE id IN ($in)");}}
}
